name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run cargo tests
        run: cargo test --verbose
      - name: Wasm test node
        run: wasm-pack test --node
      - name: Wasm test chrome
        run: wasm-pack test --headless --chrome
      - name: Wasm test firefox
        run: wasm-pack test --headless --firefox
